### ISSUE TITLE
please add support for framework 4.0

### ISSUE THREAD

**Issue by sigboe** [ShendoXT/memcardrex#10]
Instructions for linux says that get mono from upstream to get newer compatibility. But mono has come such a long way that from their website or from the package manager of distros such a new build of mono is included that framework 3.5 is totally depricated.

I successfully managed to build it on fedora just fine using

```
xbuild /property:TargetFrameworkVersion=v4.0
mono "./MemcardRex/obj/GTKsharp debug/MemcardRex.exe"
```

I didn't put the program trough a full battery of tests, but I did copy a PS1 save from a PS1 save card to a USB stick using a PS2. Then copy it to the PC and make a PCSXr compatible memorycard inclduing that save and scp it to my PS Classic. And it did work.

**Comment by hazrpg** [comment]
I can confirm compiling for mono and .net framework 4.0 works flawless - all I had to install was mono-devel (as per ubuntu 20.04's default repo). It compiled/built and ran fine.

The only issue I see is the open dialogue doesn't display the quick access buttons icons next to the dropdown - but totally workable without.

I'm going to try and build an arduino memory card reader and see if it picks it up and lets me backup my memory cards. It'd be great if this works without having to go into Windows to do it.

**Comment by ShendoXT** [comment]
Done - 234227dc20e1ebb623cdfec8083e602e790ebaa7
