### ISSUE TITLE
adding .srm filter to file open dialog

### ISSUE THREAD

**Issue by zaaans** [ShendoXT/memcardrex#11]
the standard psx emulator of retropie is lr-pcsx-rearmed, as you can see here:
https://retropie.org.uk/docs/Playstation-1/

this emulator uses .mcr files, but the files instead get the ".srm"-extension.
srm means eventually "Super Nintendo ROM Save File", but not in this context,
.srm files of this emulator are successfully loaded by the application.

So, can we add the extension .srm as "lrpcsx-readmed mcr-File" to the filter list of the file open dialog? would be a nice simple addition

**Comment by oxr463** [comment]
That format is also used by RetroArch.

**Comment by ShendoXT** [comment]
Done - aeaaecd87aa8ef20eae545b06ad6433b3a4d0135
