### ISSUE TITLE
[Feature Request] PS3 Memory Card Adapter Support

### ISSUE THREAD

**Issue by Ziginox** [ShendoXT/memcardrex#15]
Would it be possible for memcardrex to support the PS3 memory card adapter? There are some other pieces of software that can do it, of course, but they're not nearly as versatile as memcardrex. Then again, maybe formatting a card using the adapter isn't possible?
Anyway, it would be a pretty cool addition to an already awesome utility!

**Comment by ShendoXT** [comment]
Just added as of a3fe657 thanks to @ndepoel. You can grab compiled archive from Releases.
