### ISSUE TITLE
New memory cards lack the 'MC' header

### ISSUE THREAD

**Issue by bodgit** [ShendoXT/memcardrex#18]
According to memory card format documentation such as https://www.psdevwiki.com/ps3/PS1_Savedata and http://problemkaputt.de/psx-spx.htm#memorycarddataformat the header frame should be 'MC', 125 x 0x00 bytes and a 0x0e checksum byte. Looking at a memory card created with 1.9.2b7a018 it is just 128 x 0x00 bytes.

**Comment by ShendoXT** [comment]
Totally my fault, it's a bug. Will fix it.
