### ISSUE TITLE
POPS virtual Memory Card(*.VMC)

### ISSUE THREAD

**Issue by alexey-gamov** [ShendoXT/memcardrex#28]
POPS starter homebrew app for emulation PS1 games on PS2 utilizes VMC format per game.

MemcardDex already supports read-write operations, but this format is missing in file select dialog. Workaround is to select all files.

Is it possible to add this filetype?

**Comment by alextrevisan** [comment]
Pull request sent!

**Comment by ShendoXT** [comment]
Added as of [b9a6034](https://github.com/ShendoXT/memcardrex/commit/b9a6034cc1ca86dd7dc9a044567516bf43447592)
