### ISSUE TITLE
supporting PS2 MC readers (for use with PS1 memcards) in memcardrex

### ISSUE THREAD

**Issue by sl1pkn07** [ShendoXT/memcardrex#34]
Hi, can i use PS2 MC readers like 

https://www.amazon.es/Logic-ps2-ps3-Memory-Card-Adapter-Adaptador/dp/B000RMRNSI
and
https://www.amazon.com.au/PS2-Memory-Card-Data-Transfer/dp/B00107LDT4

with memcardrex?

greetings

**Comment by ShendoXT** [comment]
As @ndepoel already said I doubt it. Those third party adapters are sh#t. You can use official PS3 MC adapter which is tested and working or you can use Memcarduino. There are people selling already built units so it's all plug and play.
I don't get a dime out of it but hey, it exists. Search for "PS1 memory card reader" on aliexpress for example.
