### ISSUE TITLE
Source for plugins?

### ISSUE THREAD

**Issue by KevinEady** [ShendoXT/memcardrex#4]
Hello. I'm looking to make a plugin for editing a save. I see `Plugin interface.cs` in the `Plugins` folder but I think it would be beneficial to have some source code as a guide/reference?

Thanks, Kevin

**Comment by ShendoXT** [comment]
Hi.

Yes, you are right.
I created a repository with plugin sources: https://github.com/ShendoXT/memcardrex-plugins

Hope it helps.
