### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by 10522** [ShendoXT/memcardrex#41]
I found an old version of [MemcardRex](https://mega.nz/file/KllllRQa#Oj6efIXyLwFhdbwfOASe4DM8-_MHKyhhjPackwIbMKM) with Russian translation. I tried to contact its author, but he does not answer me. Is it possible to add this translation to the latest version of MemcardRex? I can help with translating missing strings.

**Comment by ShendoXT** [comment]
Translations are a PITA. Before I was making software with multiple languages and each time I made a new release I had to gather all the authors of each of the translation files to translate new strings. It gets cumbersome after a while.
This hacked MemcardRex binary serves me no purpose either. I'd have to decompile my own hacked software and reimplement those strings in the language I don't speak... Sorry but multilingual app support is a can of worms I don't want to open.
