### ISSUE TITLE
Kinda big requirements

### ISSUE THREAD

**Issue by grepwood** [ShendoXT/memcardrex#45]
Why is .NET Framework exactly needed in a program for editing 128KiB flash cards?

**Comment by ShendoXT** [comment]
What is the issue exactly? .NET framework runtime comes preinstalled since Windows Vista...

**Comment by grepwood** [comment]
The issue is that .NET's idea of cross-platform support is that it supports all versions of Windows from XP to 7. I see this is a mostly Windows project so I'm just gonna drop this.
