### ISSUE TITLE
writing to mem card

### ISSUE THREAD

**Issue by tommojphillips** [ShendoXT/memcardrex#53]
hey can you write to the memory card using this?

**Comment by tommojphillips** [comment]
really what i want to know is if i could install free mc boot on to a memory card using this

**Comment by alex-free** [comment]
> really what i want to know is if i could install free mc boot on to a memory card using this

You can I do with a PS3MCA.

**Comment by tommojphillips** [comment]
ive got a memory card hooked up an arduino, is it as simple as writing the .elf to the memory carD?

**Comment by alex-free** [comment]
> ive got a memory card hooked up an arduino, is it as simple as writing the .elf to the memory carD?

No, you need to use something like FreePSXBoot builder to create a memory card image that loads the executable. https://github.com/brad-lin/FreePSXBoot/tree/master/builder

**Comment by tommojphillips** [comment]
thanks man

**Comment by ShendoXT** [comment]
If you want to write to PS1 Memory Cards then yes, as @alex-free already explained you can use it.
If you want to write to PS2 Memory Cards then no. PS2 cards are not supported by MemcardRex.

**Comment by tommojphillips** [comment]
Yes Free Mc Boot

**Comment by tommojphillips** [comment]
Not psxboot

**Comment by tommojphillips** [comment]
do you guys know where i can get a dump of a FMCB memory card?
